package Conversor.IGU;

import Conversor.Logica.Servicios.ConversorServicios;

/**
 * Interface gráfica del Conversor de sólidos y líquidos
 * @author Juan Seura
 */
public class ConversorSolidosYLiquidos extends javax.swing.JFrame {

    public ConversorSolidosYLiquidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * Este método es lamado desde el constructor para inicializar el Jform. 
     * ADVERTENCIA: No modificar este código. El contenido de este método es 
     * siempre generado por el Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbUnidadMedida1S = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbUnidadMedida2S = new javax.swing.JComboBox<>();
        btnConvertirS = new javax.swing.JButton();
        txtResultadoS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        Cantidad2 = new javax.swing.JLabel();
        txtCantidadL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbUnidadMedidal1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbUnidadMedidaL2 = new javax.swing.JComboBox<>();
        btnConvertirL = new javax.swing.JButton();
        txtResultadoL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sólidos");

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        jLabel2.setText("Cantidad: ");

        txtCantidadS.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        txtCantidadS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadS.setText(" ");

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        jLabel3.setText("Convertir de: ");

        cmbUnidadMedida1S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gramo SMD", "kilogramo SMD", "onza IMP", "libra IMP", "stone IMP", "taza COC", "cucharada COC", "cucharadita COC" }));

        jLabel4.setText("a: ");

        cmbUnidadMedida2S.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gramo SMD", "kilogramo SMD", "onza IMP", "libra IMP", "stone IMP", "taza COC", "cucharada COC", "cucharadita COC" }));

        btnConvertirS.setText("Convertir");
        btnConvertirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirSActionPerformed(evt);
            }
        });

        txtResultadoS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultadoS.setText("0");

        txtMensaje.setColumns(20);
        txtMensaje.setRows(5);
        jScrollPane1.setViewportView(txtMensaje);

        Cantidad2.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        Cantidad2.setText("Cantidad: ");

        txtCantidadL.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        txtCantidadL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantidadL.setText(" ");

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 16)); // NOI18N
        jLabel5.setText("Convertir de: ");

        cmbUnidadMedidal1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mililitro SMD", "litro SMD", "taza COC", "cucharada COC", "cucharadita COC" }));
        cmbUnidadMedidal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUnidadMedidal1ActionPerformed(evt);
            }
        });

        jLabel6.setText("a: ");

        cmbUnidadMedidaL2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mililitro SMD", "litro SMD", "taza COC", "cucharada COC", "cucharadita COC" }));

        btnConvertirL.setText("Convertir");
        btnConvertirL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirLActionPerformed(evt);
            }
        });

        txtResultadoL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultadoL.setText("0");

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Líquidos");

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Conversor/IGU/Img/hogar.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(btnHome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConvertirS, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbUnidadMedida1S, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbUnidadMedida2S, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtResultadoS, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCantidadS))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(Cantidad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConvertirL, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCantidadL)
                                .addGap(28, 28, 28))
                            .addComponent(cmbUnidadMedidal1, 0, 211, Short.MAX_VALUE)
                            .addComponent(cmbUnidadMedidaL2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtResultadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(622, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadS)
                    .addComponent(Cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbUnidadMedida1S, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(cmbUnidadMedidal1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbUnidadMedidaL2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbUnidadMedida2S, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultadoS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertirS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertirL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultadoL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome))
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(216, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(184, 184, 184)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        /**
        * Botón ConvertirS que Convierte los sólidos 
        * Tomo los valores introducidos y elegidos por el usuario y los trato para
        * enviar los argumentos al método convertirSolidos(). 
        * Antes debo separar el sistema de medida, de la unidad de medida que 
        * están en el mismo objeto. Por eso realizo la extracción de la cadena en
        * dos valores, y luego con esa cadena creo dos subcadenas que dejan en
        * dos variables diferentes el sistema y la unidad de medida. 
        * Este procedimiento pudo realizarse en la lógica, pero tomé la decisión 
        * de anticiparme para trabajar allí con los datos que llegan por parámetro. 
        * El método conversor devuelve un Array con el resultado de la conversión, 
        * y un mensaje de acuerdo a si la operación se realizó con éxito o no. 
        * @param evt 
         * @param evt 
         */
    private void btnConvertirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirSActionPerformed
        ConversorServicios conversor = new ConversorServicios();
        String valorA = (String)cmbUnidadMedida1S.getSelectedItem();
        String valorB = (String)cmbUnidadMedida2S.getSelectedItem();
        String sistema1 = valorA.substring(valorA.length()-3, valorA.length());
        String sistema2 = valorB.substring(valorB.length()-3, valorB.length());
        String unidadDeMedida1 = valorA.substring(0, valorA.length()-4);
        String unidadDeMedida2 = valorB.substring(0, valorB.length()-4);
        String catidad = txtCantidadS.getText();
        String[] resultado = conversor.convertirSolidos(sistema1, sistema2, unidadDeMedida1, unidadDeMedida2, catidad);
        txtResultadoS.setText(resultado[0]);
        txtMensaje.setText(resultado[1]);
        
        
    }//GEN-LAST:event_btnConvertirSActionPerformed
        /**
        * Botón ConvertirL que Convierte los líquidos
        * Tomo los valores introducidos y elegidos por el usuario y los trato para
        * enviar los argumentos al método convertirLiquidos(). 
        * Antes debo separar el sistema de medida, de la unidad de medida que 
        * están en el mismo objeto. Por eso realizo la extracción de la cadena en
        * dos valores, y luego con esa cadena creo dos subcadenas que dejan en
        * dos variables diferentes el sistema y la unidad de medida. 
        * Este procedimiento pudo realizarse en la lógica, pero tomé la decisión 
        * de anticiparme para trabajar allí con los datos que llegan por parámetro. 
        * El método conversor devuelve un Array con el resultado de la conversión, 
        * y un mensaje de acuerdo a si la operación se realizó con éxito o no. 
        * @param evt 
         * @param evt 
         */
    private void btnConvertirLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirLActionPerformed
        ConversorServicios conversor = new ConversorServicios();
        String valorA = (String)cmbUnidadMedidal1.getSelectedItem();
        String valorB = (String)cmbUnidadMedidaL2.getSelectedItem();
        String sistema1 = valorA.substring(valorA.length()-3, valorA.length());
        String sistema2 = valorB.substring(valorB.length()-3, valorB.length());
        String unidadDeMedida1 = valorA.substring(0, valorA.length()-4);
        String unidadDeMedida2 = valorB.substring(0, valorB.length()-4);
        String catidad = txtCantidadL.getText();
        String[] resultado = conversor.convertirLiquidos(sistema1, sistema2, unidadDeMedida1, unidadDeMedida2, catidad);
        txtResultadoL.setText(resultado[0]);
        txtMensaje.setText(resultado[1]);
    }//GEN-LAST:event_btnConvertirLActionPerformed

    private void cmbUnidadMedidal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUnidadMedidal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUnidadMedidal1ActionPerformed
     /**
     * Botón para retornar al menú principal, y ocultar esta sección del programa
     * @param evt 
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    
    //Declaración de variables . No Modificar
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad2;
    private javax.swing.JButton btnConvertirL;
    private javax.swing.JButton btnConvertirS;
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox<String> cmbUnidadMedida1S;
    private javax.swing.JComboBox<String> cmbUnidadMedida2S;
    private javax.swing.JComboBox<String> cmbUnidadMedidaL2;
    private javax.swing.JComboBox<String> cmbUnidadMedidal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadL;
    private javax.swing.JTextField txtCantidadS;
    private javax.swing.JTextArea txtMensaje;
    private javax.swing.JTextField txtResultadoL;
    private javax.swing.JTextField txtResultadoS;
    // End of variables declaration//GEN-END:variables
}
